backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "config"
    label: "Site Configuration"
    files:
      - file: "public/data/siteConfig.json"
        label: "Site Settings"
        name: "site"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Logo URL", name: "logo", widget: "string"}
          - {label: "Site Abbreviation", name: "abbreviation", widget: "string"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Contact Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}
          - label: "Partner Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Company", name: "company", widget: "string"}
              - {label: "Avatar", name: "avatar", widget: "image"}
              - {label: "Testimonial", name: "testimonial", widget: "text"}

  - name: "about"
    label: "À propos"
    files:
      - file: "public/data/about.json"
        label: "À propos Content"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Mission", name: "mission", widget: "text"}
          - label: "Values"
            name: "values"
            widget: "list"
            field: {label: "Value", name: "value", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}

  - name: "hero"
    label: "Hero Section"
    files:
      - file: "public/data/heroContent.json"
        label: "Hero Content"
        name: "hero"
        fields:
          - {label: "Main Title", name: "mainTitle", widget: "string"}
          - {label: "Highlighted Word", name: "highlightedWord", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Primary Button Text", name: "primaryButtonText", widget: "string"}
          - {label: "Secondary Button Text", name: "secondaryButtonText", widget: "string"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - label: "Statistics"
            name: "stats"
            widget: "list"
            fields:
              - {label: "Number", name: "number", widget: "number"}
              - {label: "Suffix", name: "suffix", widget: "string"}
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Icon", name: "icon", widget: "string"}

  - name: "about"
    label: "About Section"
    files:
      - file: "public/data/aboutContent.json"
        label: "About Content"
        name: "about"
        fields:
          - {label: "Section Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Extended Description", name: "extendedDescription", widget: "text"}
          - {label: "About Image", name: "image", widget: "image"}
          - label: "Missions"
            name: "missions"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}

  - name: "startups"
    label: "Startups"
    files:
      - file: "public/data/startups.json"
        label: "Startups Collection"
        name: "startups"
        fields:
          - label: "Startups"
            name: "startups"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "URL", name: "url", widget: "string"}

  - name: "events"
    label: "Events"
    files:
      - file: "public/data/events.json"
        label: "Events Collection"
        name: "events"
        fields:
          - label: "Events"
            name: "events"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime"}
              - {label: "Location", name: "location", widget: "string"}
              - {label: "Description", name: "description", widget: "markdown"}

  - name: "news"
    label: "News & Articles"
    files:
      - file: "public/data/news.json"
        label: "News Collection"
        name: "news"
        fields:
          - label: "Articles"
            name: "articles"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date", name: "date", widget: "datetime"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Content", name: "content", widget: "markdown"}

  - name: "partners"
    label: "Partners"
    files:
      - file: "public/data/partners.json"
        label: "Partners Collection"
        name: "partners"
        fields:
          - label: "Partners"
            name: "partners"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "URL", name: "url", widget: "string"}

  - name: "resources"
    label: "Resources"
    files:
      - file: "public/data/resources.json"
        label: "Resources Collection"
        name: "resources"
        fields:
          - label: "Resources"
            name: "resources"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Type", name: "type", widget: "string"}
              - {label: "File", name: "file", widget: "file"}
              - {label: "Description", name: "description", widget: "text"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "public/data/membership.json"
        label: "Membership Plans"
        name: "membership"
        fields:
          - label: "Plans"
            name: "plans"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Price", name: "price", widget: "string"}
              - {label: "Period", name: "period", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Popular", name: "popular", widget: "boolean"}
              - label: "Features"
                name: "features"
                widget: "list"
                field: {label: "Feature", name: "feature", widget: "string"}