backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "config"
    label: "Site Configuration"
    files:
      - file: "public/data/siteConfig.json"
        label: "Site Settings"
        name: "site"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "Logo URL", name: "logo", widget: "string"}
          - {label: "Site Abbreviation", name: "abbreviation", widget: "string"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Contact Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "string"}

  - name: "hero"
    label: "Hero Section"
    files:
      - file: "public/data/heroContent.json"
        label: "Hero Content"
        name: "hero"
        fields:
          - {label: "Main Title", name: "mainTitle", widget: "string"}
          - {label: "Highlighted Word", name: "highlightedWord", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Primary Button Text", name: "primaryButtonText", widget: "string"}
          - {label: "Secondary Button Text", name: "secondaryButtonText", widget: "string"}
          - {label: "Hero Image", name: "heroImage", widget: "image"}
          - label: "Statistics"
            name: "stats"
            widget: "list"
            fields:
              - {label: "Number", name: "number", widget: "number"}
              - {label: "Suffix", name: "suffix", widget: "string"}
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Icon", name: "icon", widget: "string"}

  - name: "about"
    label: "About Section"
    files:
      - file: "public/data/aboutContent.json"
        label: "About Content"
        name: "about"
        fields:
          - {label: "Section Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Extended Description", name: "extendedDescription", widget: "text"}
          - {label: "About Image", name: "image", widget: "image"}
          - label: "Missions"
            name: "missions"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}

  - name: "startups"
    label: "Startups"
    folder: "public/data/startups"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Sector", name: "sector", widget: "select", options: ["FinTech", "EdTech", "HealthTech", "AgriTech", "E-commerce", "SaaS"]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Founder", name: "founder", widget: "string"}
      - {label: "Employees", name: "employees", widget: "string"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Website", name: "website", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}

  - name: "events"
    label: "Events"
    folder: "public/data/events"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      - {label: "Time", name: "time", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Attendees", name: "attendees", widget: "string"}
      - {label: "Type", name: "type", widget: "select", options: ["Conférence", "Atelier", "Hackathon", "Pitch", "Formation"]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Status", name: "status", widget: "select", options: ["upcoming", "past"], default: "upcoming"}

  - name: "news"
    label: "News & Articles"
    folder: "public/data/news"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Innovations", "Financements", "Événements", "Portraits"]}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      - {label: "Read Time", name: "readTime", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "partners"
    label: "Partners"
    folder: "public/data/partners"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Financier", "Académique", "Institutionnel", "Incubateur", "Télécoms"]}
      - {label: "Description", name: "description", widget: "text"}

  - name: "resources"
    label: "Resources"
    folder: "public/data/resources"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["Guides", "Financements", "Juridique", "Marketing", "Technique"]}
      - {label: "Type", name: "type", widget: "select", options: ["PDF", "DOCX", "XLSX"]}
      - {label: "Size", name: "size", widget: "string"}
      - {label: "Downloads", name: "downloads", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "File", name: "file", widget: "file"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "public/data/membership.json"
        label: "Membership Plans"
        name: "membership"
        fields:
          - label: "Plans"
            name: "plans"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Price", name: "price", widget: "string"}
              - {label: "Period", name: "period", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Popular", name: "popular", widget: "boolean"}
              - label: "Features"
                name: "features"
                widget: "list"
                field: {label: "Feature", name: "feature", widget: "string"}